### ISSUE TITLE
Crate regex missing as a dependency

### ISSUE THREAD

**Issue by stephanemagnenat** [Storyyeller/cubiml-demo#8]
Using Rust 1.77.2 on Ubuntu Ubuntu 22.04.4 LTS, following the instructions in the README, I get the following compilation error:
```
error[E0463]: can't find crate for `regex`
    --> src/grammar.rs:9329:5
     |
9329 |     extern crate regex as ___regex;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

Adding the `regex` crate as a dependency in `Cargo.toml` solves the problem.

**Comment by Storyyeller** [comment]
Which version of lalrpop are you using? It works fine for me with 0.19.4.

**Comment by Storyyeller** [comment]
After updating to lalrpop 20.2, I get an error, but it's a different error than what you posted (`method `expected_tokens_from_states` is not a member of trait `___state_machine::ParserDefinition``)

**Comment by Storyyeller** [comment]
I updated the code so it compiles fine with 0.20.2 for me. Still no regex problems, just a renamed enum variant. Please let me know if you still have trouble building it.
